language: go
go:
    - master

# install - install any dependencies required
install:
    - go get github.com/gohugoio/hugo

script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "2a792eb93ce4"
  - COMMIT_AUTHOR_EMAIL: "remco@dutchcoders.io"
